spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  messages:
    encoding: UTF-8

server:
  port: 8080
  servlet:
    context-path: /api

cors:
  allowed-origins: http://localhost:3000

logging:
  level:
    org:
      jooq: DEBUG
